#!/bin/sh

### BEGIN INIT INFO
# Provides:          uptime-tracker
# Required-Start:    $remote_fs $time
# Required-Stop:     $remote_fs $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start uptime-tracker in auto mode
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
INTERVAL=5

[ -r /etc/default/uptime-tracker ] && . /etc/default/uptime-tracker

DAEMON=/usr/bin/uptime-tracker
PIDFILE=/var/run/uptime-tracker.pid

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemon is there
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting uptime-tracker in auto mode" "uptime-tracker"

		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $OPTS auto $INTERVAL

		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping uptime-tracker" "uptime-tracker"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		;;

	restart|force-reload)
		$0 stop && sleep 2 && $0 start
		;;

	status)
		status_of_proc -p $PIDFILE $DAEMON uptime-tracker && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/uptime-tracker {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac
